Update index.test.js
Removed Promisfy import.

To fix this transpile issue:

 FAIL  node_modules/gensync/test/index.test.js [ node_modules/gensync/test/index.test.js ]
Error: Cannot find module 'util.promisify'
Require stack:
- C:\Users\mayank.bhugra\Documents\node_modules\gensync\test\index.test.js
 ❯ Object.<anonymous> node_modules/gensync/test/index.test.js:3:19